version : '3.3'
services :
  pycharm :
    environment :
      - 'DISPLAY=${DISPLAY}'
    volumes :
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '/dev/shm/111:/home/developer'
    container_name : pycharm-aaas2
    image : jek4